name: "ga4"
version: "6.0.0"
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

  

#models:
#  ga4:
#    +materialized: view
#    marts:
#      +materialized: table

models:
  ga4:
    GA4_analysis:
      schema: GA4_analysis_dev
      +materialized: table
vars:
  ga4:
    source_project: "ga4-bigquery-412121"
    source_dataset: "analytics_261064067"
    property_ids: [261064067] # Array of properties to process
    start_date: "20240123" # Earliest date to load
    frequency: "daily+streaming" # daily|streaming|daily+streaming. See 'Export Frequency' below.
    static_incremental_days: 3 # Number of days to scan and reprocess on each run
    conversion_events: ['purchase','blog_lead_gen','brochure_request_completion','gated_offer_leads','homepage_lead_gen','location_lead_gen','manual_conversion_BOOK_APPOINTMENT','program_lead_gen','purchase_ipc','purchase_opl','purchase_ota','purchase_vtc','quiz_completion','topic_lead_gen']

